drop table SAMPLE;
drop table SAMPLE2;
create table SAMPLE(ID INT PRIMARY KEY , NAME VARCHAR(20));

INSERT INTO SAMPLE VALUES(2,'BGMI'),(3,'COC'),(4,'COD'),(5,'GTA'),(6,'ASSASSIAN CREED'),(7,'ANGRY BIRDS'),(8,'COUNTER STRIKE'),(9,'SHADOW FIGHT'),(10,'HIMAN'),(11,'PACMAN'),(12,'REAL CICKET');

create table SAMPLE2(ID2 INT PRIMARY KEY, ID INT , RELEASEYEAR VARCHAR(20), FOREIGN KEY (ID) REFERENCES SAMPLE(ID) ON UPDATE CASCADE);
INSERT INTO SAMPLE2 VALUES(10,2,'2016');

-- ALTER TABLE employee ADD CONSTRAINT emp_id UNIQUE (id);

-- ALTER TABLE SAMPLE2 ADD CONSTRAINT CUSTOMER_FK  FOREIGN KEY (ID)  REFERENCES SAMPLE(ID) ON UPDATE CASCADE ;
-- ALTER TABLE SAMPLE2 ADD CONSTRAINT UNIQUE_ID UNIQUE (ID);
-- ALTER TABLE SAMPLE2 ADD CONSTRAINT SAMPLE_FK FOREIGN KEY (ID) REFERENCES SAMPLE(ID);




